name: PostgreSQL Service Example
on:
  push:
    paths:
      - '.github/workflows/12-postgres-example.yml'

jobs:
  postgres-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          # Maps TCP port 5432 in the service container to a randomly chosen available port on the host.
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: run postgres
        run: pg_isready -h localhost